apiVersion: v1
kind: Secret
metadata:
  name: postgres-env
data:
  username: fc8252c8dc55839967c58b9ad755a59b61b67c13227ddae4bd3f78a38bf394f7
  password: fc8252c8dc55839967c58b9ad755a59b61b67c13227ddae4bd3f78a38bf394f7
  database: webserver